export enum StatusCode {
    SUCCESS = 'SUCCESS',
    NO_ROWS_FOUND = 'NO_ROWS_FOUND',
    ONE_ROW_FOUND = 'ONE_ROW_FOUND',
    INVALID_INPUT = 'INVALID_INPUT',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_PERMISSION = 'INVALID_PERMISSION',
    INVALID_PASSWORD = 'INVALID_PASSWORD',
    NULL_OBJECT = 'NULL_OBJECT',
    ERROR = 'ERROR'
}
